# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: publishOverride
  displayName: Publish Override
  type: string
  default: default
  values:
    - default
    - skip
- name: releaseBuildOverride
  displayName: Release Build Override
  type: string
  default: default
  values:
    - default
    - false
    - true

trigger:
  - master
  - test
  
pr: none
  
pool:
  vmImage: 'ubuntu-latest'

variables:
- group: secret
- template: include-vars.yml
  parameters:
    publishOverride: ${{ parameters.publishOverride }}
    releaseBuildOverride: ${{ parameters.releaseBuildOverride }}

steps:
- checkout: self
  persistCredentials: false
  clean: true
  fetchDepth: 1
- script: |
    git status
    git tag blah-$(Build.BuildId)
    git tag
    git remote -vv
    # git push origin blah-$(Build.BuildId)

    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    npm version patch


    git push origin HEAD:$(Build.SourceBranch)
  displayName: 'Push tag'

