# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- release/*
- refs/tags/*

pr:
- master
- release/*
- unknown

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: skipComponentGovernanceDetection
    value: true

stages:
- stage: build
  jobs:
    - job: A
      steps:


      - script: |
          echo "##vso[task.setvariable variable=blah;isOutput=true]true"
        displayName: 'Set variable'
        name: setVar
      - script: echo $(setVar.blah)
        displayName: 'Get variable'
    - job:
      dependsOn: A
      variables:
        blah: $[ dependencies.A.outputs['setVar.blah'] ]
      condition: eq(variables.blah, true)
      steps:
      - script: echo Hello, world 1 $(blah)
        displayName: 'Run a one-line script'
    - job:
      dependsOn: A
      variables:
        blah: $[ dependencies.A.outputs['setVar.blah'] ]
      condition: eq(variables.blah, false)
      steps:
      - script: echo Hello, world 2 $(blah)
        displayName: 'Run a one-line script'
    - job:
      dependsOn: A
      variables:
        blah: $[ dependencies.A.outputs['setVar.blah'] ]
      steps:
      - script: echo Hello, world 3 $(blah)
        displayName: 'Run a one-line script'

- stage: publish
  dependsOn: build
  jobs:
  - deployment: B
    displayName: "B"
    environment: npm-feed
    strategy: 
      runOnce:
        deploy:
          steps:
            # No need to explicitly pass the connection details
          - script: echo deployment $(Build.Id)
