# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- release/*
- refs/tags/*

pr:
- master
- release/*
- unknown

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: skipComponentGovernanceDetection
    value: true

stages:
- stage: build
  jobs:
    - job:
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'

- stage: publish
  dependsOn: build
  jobs:
  - deployment: B
    displayName: "B"
    environment: npm-feed
    strategy: 
      runOnce:
        deploy:
          steps:
            # No need to explicitly pass the connection details
          - script: echo deployment $(Build.Id)
