# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: p1
      source: Build
      trigger:
        branches:
          include:
          - master
    - pipeline: p2
      source: Build - common-utils
      trigger:
        branches:
          include:
          - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: skipComponentGovernanceDetection
    value: true

stages:
- stage: build
  jobs:
    - job: A
      steps:
      - script: |
          echo "##vso[task.setvariable variable=blah;isOutput=true]true"
        displayName: 'Set variable'
        name: setVar
      - script: echo $(setVar.blah)
        displayName: 'Get variable'
    - job: Yes
      dependsOn: A
      variables:
        blah: $[ dependencies.A.outputs['setVar.blah'] ]
      condition: eq(dependencies.A.outputs['setVar.blah'], true)
      steps:
      - script: echo Hello, world 1 $(blah)
        displayName: 'Run a one-line script'
    - job: No
      dependsOn: A
      variables:
        blah: $[ dependencies.A.outputs['setVar.blah'] ]
      condition: eq(dependencies.A.outputs['setVar.blah'], false)
      steps:
      - script: echo Hello, world 2 $(blah)
        displayName: 'Run a one-line script'
