# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: build   # Name of the pipeline resource
    source: Build # Name of the triggering pipeline
    trigger:
      branches:
      - master


pool:
  vmImage: 'ubuntu-latest'

variables:
- name: skipComponentGovernanceDetection
  value: true

stages:
- stage: A
  jobs:
  - job:
    steps:
    - script: echo deployment $(Build.Id)


stages:
- stage: B
  jobs:
  - job:
    steps:
    - script: echo deployment $(Build.Id)