# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: build   # Name of the pipeline resource
    source: Build # Name of the triggering pipeline
    trigger:
      branches:
      - master


pool:
  vmImage: 'ubuntu-latest'

jobs:
- deployment: blah
  displayName: "blah"
  strategy: 
    runOnce:
      deploy:
        steps:
          # No need to explicitly pass the connection details
        - script: echo deployment $(Build.Id)